title: 八木田 樹 (Miki Yagita)
author: "Miki Yagita"
description: "Curriculum Vitae and Publications."

baseurl: ""
url: "https://myagita.github.io"
header_pages: []

theme: minima
plugins:
  - jekyll-feed

google_analytics: G-P57F94KJJE
